<!DOCTYPE html>
	<!--[if lt IE 7]><html class="lt-ie9 lt-ie8 lt-ie7 no-js fixed-header" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><![endif]-->
	<!--[if IE 7]><html class="lt-ie9 lt-ie8 no-js fixed-header" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><![endif]-->
	<!--[if IE 8]><html class="lt-ie9 no-js fixed-header" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><![endif]-->
	<!--[if gt IE 8]><!--><html class="no-js fixed-header" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]-->
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

		<link rel="stylesheet" href="css/normalize.css" />
		<link rel="stylesheet" href="css/foundation.css" />
		<link rel="stylesheet" href="css/foundation-grid-ie8.css" />
		<link rel="stylesheet" href="css/off-canvas.css" />
		<link rel="stylesheet" href="css/app.css">

		<script src="js/custom.modernizr.js"></script>
		<title>NYS Career Center Locator</title>
	</head>
	<body>
		<div class="site" id="site">
			<div class="gov-wrap">
				<a href="#" class="open-menu menu-icon" id="open-menu" >
					<img alt="Site Menu" src="images/menu.png" />
				</a>
				<h1>NYS Career Center Locator</h1>
				<a href="http://www.ny.gov/" class="nys-icon">
					<img alt="" src="images/new-york-state-image.png" />
				</a>
			</div>	
		</div>
		<div class="main-nav">
			<div class="nav-wrap">
				<div class="main-nav-controls">
					<form class="main-nav-search">
						<input type="text" class="menu-search-box" name="q" />
						<input type="submit" class="menu-search-button" value="Go" />
					</form>
				</div>
				<div class="main-nav-contents">
					<a href="./">Find a Career Center</a>
					<a href="http://labor.ny.gov/careerservices/CareerServicesIndex.shtm" target="_blank">Job Seeker Assistance</a>
					<a href="http://jobzone.ny.gov/" target="_blank">JobZone</a>
					<a href="http://careerzone.ny.gov/" target="_blank">CareerZone</a>
					<a href="http://laborny.jobs" target="_blank">Job Openings</a>
				</div>
				<div class="connect-with-us-div">
					<span class="connect-with-us">
						<a href="https://www.facebook.com/nyslabor" target="_blank" class="facebook"></a>
				<a href="https://twitter.com/nyslabor" target="_blank" class="twitter"></a>
				<a href="http://www.youtube.com/user/NYSLabor" target="_blank" class="youtube"></a>
				<a href="http://www.flickr.com/photos/nyslabor/" target="_blank" class="flickr"></a>
					</span>
				</div>
			</div>
		</div>
	</div>	