<div class="row footer">
	<div class="large-12 columns centered">
		<div class="footer-wrap">
			<span class="connect-with-us-footer">
				<a href="https://www.facebook.com/nyslabor" target="_blank" class="facebook"></a>
				<a href="https://twitter.com/nyslabor" target="_blank" class="twitter"></a>
				<a href="http://www.youtube.com/user/NYSLabor" target="_blank" class="youtube"></a>
				<a href="http://www.flickr.com/photos/nyslabor/" target="_blank" class="flickr"></a>
			</span>
		</div>
	</div>
</div>